#!/bin/bash

# Title: imagedownload
# Author: Caleb Kitzmann
# Description: This bash script makes a directory called notebook_<num> and
#              changes into that directory. It then loops through each url
#              within a certain range of manuscript numbers and then does a wget
#              command on the url which downloads the images to the new
#              directory.

# echo Specify notebook and manuscript number seperated by a space
# read notebook_num manu_num
echo Specify start and end notebook as well as intial manuscript number
read start_notebook end_notebook start_manu

for notebook_num in $(seq $start_notebook $end_notebook)
do
  cd ../mf-angular/src/assets/images/
  rm -rf notebook_$notebook_num
  mkdir notebook_$notebook_num
  cd notebook_$notebook_num

  manu_num=$start_manu

  for url in 'http://tundra.csd.sc.edu/vllc/img/field_scans/add_ms_'${manu_num}'/JPEG/Add_ms_'${manu_num}'_'{001..700}'.jpg'
  do
    if wget "$url"
    then
      failed=
    elif [ "$failed" ]
    then
      break
    else
      failed=yes
    fi
  done

  for url in 'http://tundra.csd.sc.edu/vllc/img/field_scans/add_ms_'${manu_num}'/JPEG/add_ms_'${manu_num}'-'{001..700}'.jpg'
  do
    if wget "$url"
    then
      failed=
    elif [ "$failed" ]
    then
      break
    else
      failed=yes
    fi
  done

  let "start_manu++"
  cd ..
done
